/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.isen.tp.myhttp
import com.github.kittinunf.fuel.httpGet
import kotlin.concurrent.thread

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {


//    "http://httpbin.org/get".httpGet().responseString { request, response, result ->
//        if (response.statusCode == 200) {
//            println(response)
//        } else {
//            println("Error ${response.responseMessage}")
//        }
//        println(request)
//        println(response)
//        println(result)
//    }
//    Thread.sleep(500)

    "https://jsonplaceholder.typicode.com/posts".httpGet(listOf(

        "userid" to "2"
    )
    ).responseObject(Post.Deserializer()) { request, response, result ->
        val (posts, err) = result
        if (err != null) {
            println("Error ${err.response.responseMessage}")
        } else {
            println(posts)
        }
    }
    Thread.sleep(500)
}
